/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    customers: Customer;
    claims: Claim;
    conversations: Conversation;
    'knowledge-articles': KnowledgeArticle;
    media: Media;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    claims: ClaimsSelect<false> | ClaimsSelect<true>;
    conversations: ConversationsSelect<false> | ConversationsSelect<true>;
    'knowledge-articles': KnowledgeArticlesSelect<false> | KnowledgeArticlesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  displayName?: string | null;
  /**
   * Access role of the user
   */
  role: 'admin' | 'ai-agent' | 'human-agent';
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * Customers of the insurance company
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  fullName?: string | null;
  firstName: string;
  lastName: string;
  /**
   * Date of birth of the customer
   */
  dob?: string | null;
  /**
   * Email of the customer
   */
  email: string;
  /**
   * E.164 format preferred
   */
  phone?: string | null;
  /**
   * Mailing address of the customer. For MVP, we assume all customers live in the US.
   */
  address: {
    line1: string;
    line2?: string | null;
    city: string;
    state: string;
    postalCode: string;
  };
  /**
   * Policy number of the customer
   */
  policyNumber?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Track insurance claims for Observe Insurance customers.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "claims".
 */
export interface Claim {
  id: number;
  /**
   * Automatically generated OBS reference number.
   */
  claimNumber: string;
  /**
   * Customer associated with this claim.
   */
  customer: number | Customer;
  /**
   * Lifecycle status of the claim.
   */
  status: 'pending' | 'documentation' | 'review' | 'approved' | 'denied' | 'completed' | 'cancelled';
  /**
   * Date of loss or incident if known.
   */
  incidentDate?: string | null;
  /**
   * Estimated claim amount in USD.
   */
  amount?: number | null;
  coverageType?: ('property' | 'liability' | 'flood' | 'fire' | 'other') | null;
  /**
   * Location details for the incident.
   */
  lossLocation?: {
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
  };
  /**
   * Automatically generated summary kept in sync with claim details.
   */
  description?: string | null;
  /**
   * Free-form notes captured during intake.
   */
  additionalDetails?: string | null;
  /**
   * Files and evidence uploaded for the claim.
   */
  attachments?:
    | {
        file: number | Media;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Chronological notes about claim handling.
   */
  caseNotes?:
    | {
        title: string;
        body: string;
        source: 'agent' | 'system' | 'customer';
        createdAt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Evidence, forms, photos, PDFs
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  label?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Call recordings and transcripts from ElevenLabs Conversational AI
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversations".
 */
export interface Conversation {
  id: number;
  /**
   * ElevenLabs conversation ID
   */
  conversationId: string;
  /**
   * ElevenLabs agent ID
   */
  agentId: string;
  /**
   * Linked customer if identified during call
   */
  customer?: (number | null) | Customer;
  /**
   * Customer name from conversation (if not linked to customer record)
   */
  customerName?: string | null;
  /**
   * Phone number from Vonage
   */
  customerPhone?: string | null;
  /**
   * Vonage call UUID
   */
  callUuid?: string | null;
  /**
   * Vonage conversation UUID
   */
  conversationUuid?: string | null;
  status: 'in_progress' | 'completed' | 'failed' | 'disconnected';
  /**
   * Call duration in seconds
   */
  duration?: number | null;
  startTime?: string | null;
  endTime?: string | null;
  /**
   * Full conversation transcript
   */
  transcript?:
    | {
        timestamp?: string | null;
        speaker: 'user' | 'agent';
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * AI-generated summary of the conversation
   */
  summary?: string | null;
  /**
   * List of tools/functions called during conversation
   */
  toolsCalled?:
    | {
        toolName: string;
        timestamp?: string | null;
        parameters?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        result?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Additional conversation metadata
   */
  metadata?: {
    authenticated?: boolean | null;
    verificationMethod?: ('phone' | 'email' | 'name_dob' | 'none') | null;
    /**
     * Claim numbers mentioned in conversation
     */
    claimsDiscussed?:
      | {
          claimNumber?: string | null;
          id?: string | null;
        }[]
      | null;
    intent?: ('claim_status' | 'file_claim' | 'upload_documents' | 'general_inquiry' | 'other') | null;
    sentiment?: ('positive' | 'neutral' | 'negative') | null;
  };
  /**
   * Call analytics and metrics
   */
  analytics?: {
    totalMessages?: number | null;
    userMessages?: number | null;
    agentMessages?: number | null;
    averageResponseTime?: number | null;
    interruptionCount?: number | null;
  };
  /**
   * Raw webhook payload from ElevenLabs
   */
  rawData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Knowledge base content powering FAQ responses.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "knowledge-articles".
 */
export interface KnowledgeArticle {
  id: number;
  title: string;
  /**
   * URL-friendly slug used to reference this article.
   */
  slug: string;
  /**
   * Controls whether the article is available for assistants.
   */
  status?: ('draft' | 'published' | 'archived') | null;
  /**
   * Short synopsis displayed in search results.
   */
  summary?: string | null;
  /**
   * Choose how to provide the main article content.
   */
  contentSource?: ('richText' | 'plainText' | 'document') | null;
  /**
   * Primary knowledge base content. Supports headings, lists, and links.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Upload a supporting PDF or document stored in Media.
   */
  sourceDocument?: (number | null) | Media;
  /**
   * Plain text used for embeddings. Required for plain text or document sources.
   */
  plainTextOverride?: string | null;
  tags?:
    | {
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'knowledge-articles';
    value: number | KnowledgeArticle;
  };
  /**
   * Short excerpt for search results
   */
  excerpt?: string | null;
  /**
   * Full searchable content
   */
  content?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'claims';
        value: number | Claim;
      } | null)
    | ({
        relationTo: 'conversations';
        value: number | Conversation;
      } | null)
    | ({
        relationTo: 'knowledge-articles';
        value: number | KnowledgeArticle;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  displayName?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  fullName?: T;
  firstName?: T;
  lastName?: T;
  dob?: T;
  email?: T;
  phone?: T;
  address?:
    | T
    | {
        line1?: T;
        line2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
      };
  policyNumber?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "claims_select".
 */
export interface ClaimsSelect<T extends boolean = true> {
  claimNumber?: T;
  customer?: T;
  status?: T;
  incidentDate?: T;
  amount?: T;
  coverageType?: T;
  lossLocation?:
    | T
    | {
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
      };
  description?: T;
  additionalDetails?: T;
  attachments?:
    | T
    | {
        file?: T;
        description?: T;
        id?: T;
      };
  caseNotes?:
    | T
    | {
        title?: T;
        body?: T;
        source?: T;
        createdAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversations_select".
 */
export interface ConversationsSelect<T extends boolean = true> {
  conversationId?: T;
  agentId?: T;
  customer?: T;
  customerName?: T;
  customerPhone?: T;
  callUuid?: T;
  conversationUuid?: T;
  status?: T;
  duration?: T;
  startTime?: T;
  endTime?: T;
  transcript?:
    | T
    | {
        timestamp?: T;
        speaker?: T;
        text?: T;
        id?: T;
      };
  summary?: T;
  toolsCalled?:
    | T
    | {
        toolName?: T;
        timestamp?: T;
        parameters?: T;
        result?: T;
        id?: T;
      };
  metadata?:
    | T
    | {
        authenticated?: T;
        verificationMethod?: T;
        claimsDiscussed?:
          | T
          | {
              claimNumber?: T;
              id?: T;
            };
        intent?: T;
        sentiment?: T;
      };
  analytics?:
    | T
    | {
        totalMessages?: T;
        userMessages?: T;
        agentMessages?: T;
        averageResponseTime?: T;
        interruptionCount?: T;
      };
  rawData?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "knowledge-articles_select".
 */
export interface KnowledgeArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  summary?: T;
  contentSource?: T;
  content?: T;
  sourceDocument?: T;
  plainTextOverride?: T;
  tags?:
    | T
    | {
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  label?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  excerpt?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}